### ISSUE TITLE
help pls

### ISSUE THREAD

**Issue by Pavidlo22** [thedeaddan/autobuy_minecraft#3]
Traceback (most recent call last):
  File "C:\Users\\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\\PycharmProjects\pythonProject\nemain.py", line 42, in <module>
    sleep(1)
KeyboardInterrupt

**Comment by thedeaddan** [comment]
Судя по ошибке, ты просто выключаешь его))

**Comment by Pavidlo22** [comment]
Да, но он просто не работает при запуске, хотя указал всё вроде верно
Я просто только начинаю разбираться в этом всём и если считаешь нужным, то можешь отписать в тг и помочь, буду безмерно благодарен @Ticxz9
